### ISSUE TITLE
gds-label va form label?

### ISSUE THREAD

**Issue by oxyc** [generoi/genero-design-system#49]
I wonder if label is too much of an abstraction and if we should just use it independently as a form input label instead? Currently tags and accordions use it.

Currently styling tags it's a bit annoying, as menu items used to be.

Thoughts?

**Comment by taromorimoto** [comment]
@oxyc yeah, I agree. The rational earlier was that we could have a consistent styling across the whole app and kind of enforce a strict set of typography. But as we both agree the solution for this was not very successful. Maybe the consistent styling should be done kind of manually in the css variables level instead of reusing atomic elements. 

In a way this kind of goes against the "atomic design system" idea, but maybe more correct way. So maybe those atomic level components should actually be used as they are instead of "converting them to be something else". So for example using gds-label in gds-tag would be incorrect but using gds-tag in gds-media-card would be correct.

Do you agree with this?

**Comment by oxyc** [comment]
I agree.

I think as long as they're in a slot and can be changed it also makes things way easier.
